### ISSUE TITLE
GEM doesnt produce any graphical output

### ISSUE THREAD

**Issue by amitpande74** [yguoma/GEM3#15]
Hi,
I am using chipexo data to analyze BAM files. 
I get an error at the nd of the run:
Loading genome sequences ...
/cluster/genomes/Genome is not a valid path. Use default path.
chr6_dbb_hap3.fa genome sequence file is not found at directory /cluster/genomes/Genome_chrfa_only.

the log file reads like this :
2019-10-16 15:07:45
Options:
--d Read_Distribution_ChIP-exo.txt --g hg19.chrom.sizes -- hg19/ --expt unique.bam --f BAM --out peaks --k_min 6 --k_max 36 --smooth 3 --mrc 20 
Original read count stats:
_IP  	Bases: 2419980	HitCounts: 1.8277762E7
At Poisson p-value 1.0e-03, in a 301bp window, expect 3 reads.
The genome is segmented into 191530 regions for analysis.
Running with 8 threads ...
---------------------------
Events discovered 
Significant:	53487
Insignificant:	10344
Filtered:	1618
Finish binding event prediction: 1.6m
Refine read distribution from 2000 binding events. 
Running with 8 threads ...
---------------------------
Events discovered 
Significant:	30452
Insignificant:	54181
Filtered:	4569
Finish binding event prediction: 31.5s
Refine read distribution from 2000 binding events. 
==============================================
The protein for which I am analyzing the data is 36 base pairs in binding.

Can you kindly help as to where I am going un-prescribed.
best regards.
Amit

**Comment by yguoma** [comment]
You missed the genome flag for -- hg/
--d Read_Distribution_ChIP-exo.txt --g hg19.chrom.sizes -- hg19/ --expt unique.bam --f BAM --out peaks --k_min 6 --k_max 36 --smooth 3 --mrc 20

**Comment by amitpande74** [comment]
Thanks....but what command line parameter has to be used if one wants to have the BED regions for these binding sites. Kindly help.

**Comment by yguoma** [comment]
You can use --outBED to get BED files, or --outNP to get ENCODE Narrow Peak format. See more at http://groups.csail.mit.edu/cgs/gem/#options
