### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException: Can't have a null genome

### ISSUE THREAD

**Issue by RomainBlancMathieu** [yguoma/GEM3#18]
Hi there

I am running a KMAC followed by KSM analysis on DAPseq data.
I can generate the kmer set motif using KMAC using sequences correspnding to DAP-seq peaks
but then when I try to search the KSM on these same sequences I run into the error as below.

Please help me :)
Romain

Error:

Scanning KSM motifs ...
  ... iswap_spe_w100k10k30_0.m0 ...
  ... iswap_spe_w100k10k30_0.m1 ...
  ... iswap_spe_w100k10k30_0.m2 ...
  ... iswap_spe_w100k10k30_0.m3 ...
  ... iswap_spe_w100k10k30_0.m4 ...
  ... iswap_spe_w100k10k30_0.m5 ...
  ... iswap_spe_w100k10k30_0.m6 ...
  ... iswap_spe_w100k10k30_0.m7 ...
  ... iswap_spe_w100k10k30_0.m8 ...
  ... iswap_spe_w100k10k30_0.m9 ...
Note: for motif instances on the minus strand, the SeqPos is the position on the reverse compliment of the input sequence.
Exception in thread "main" java.lang.NullPointerException: Can't have a null genome
    at edu.mit.csail.cgs.datasets.general.Region.<init>(Region.java:134)
    at edu.mit.csail.cgs.datasets.general.Region.fromString(Region.java:695)
    at edu.mit.csail.cgs.deepseq.analysis.MotifScan.findMotifInstances(MotifScan.java:254)
    at edu.mit.csail.cgs.deepseq.analysis.MotifScan.main(MotifScan.java:32)
    at edu.mit.csail.cgs.deepseq.discovery.GEM.main(GEM.java:315)

My commands are:

java -Xmx8G -jar ${GEM}/gem.jar KMAC \
    --pos_seq $POS \
    --k_win 100 \
    --k_min 10 \
    --k_max 30 \
    --k_top 10 \
    --out_name $RUN \
    --print_aligned_seqs ON \
    --gc -1 \
    --neg_seq $NEG

java -Xmx8G -jar ${GEM}/gem.jar KSM --fasta $POS --ksm ksm_list.txt --out $RUN.KSM.scan

**Comment by RomainBlancMathieu** [comment]
The error was due to the presence of ":" in the query names.
It worked after removing this character

Romain

**Comment by nevelsk90** [comment]
> The error was due to the presence of ":" in the query names.
> It worked after removing this character
> 
> Romain

I've run in the same error message. Can you elaborate please what was your solution?
Thanks in advance!

**Comment by yguoma** [comment]
I suspect there is something wrong with the --ksm ksm_list.txt file.
