### ISSUE TITLE
Can KMAC discover motifs from SELEX 20/40bp data?

### ISSUE THREAD

**Issue by joserodriguez233** [yguoma/GEM3#6]
Hi,

I do SELEX on transcriptions factors and I typically discover motifs via MEME using enriched sub-sequences (10bp/12bp). Can KMAC discover motifs in 20bp (or 40bp) SELEX data?

thanks much,
jose

**Comment by yguoma** [comment]
Hi Jose,

KMAC was designed and tested with ChIP-seq-like datasets. Usually 60-200bp, a few hundred to 10s thousand sequences. One important thing is to keep the sequence length more or less similar. I have not run it on SELEX data, but would say give it a try. 

Yuchun
